# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 681)
        MainWindow.setMinimumSize(QtCore.QSize(812, 681))
        MainWindow.setMaximumSize(QtCore.QSize(812, 681))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(186, 174, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(186, 174, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(186, 174, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(186, 174, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Texto = QtWidgets.QTextEdit(self.centralwidget)
        self.Texto.setGeometry(QtCore.QRect(300, 70, 481, 111))
        self.Texto.setObjectName("Texto")
        self.btnLimpiar = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimpiar.setGeometry(QtCore.QRect(490, 500, 111, 41))
        self.btnLimpiar.setObjectName("btnLimpiar")
        self.plainText1 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText1.setGeometry(QtCore.QRect(50, 60, 51, 20))
        self.plainText1.setMaxLength(1)
        self.plainText1.setObjectName("plainText1")
        self.plainText2 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText2.setGeometry(QtCore.QRect(50, 80, 51, 20))
        self.plainText2.setMaxLength(1)
        self.plainText2.setObjectName("plainText2")
        self.plainText4 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText4.setGeometry(QtCore.QRect(50, 120, 51, 20))
        self.plainText4.setMaxLength(1)
        self.plainText4.setObjectName("plainText4")
        self.plainText3 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText3.setGeometry(QtCore.QRect(50, 100, 51, 20))
        self.plainText3.setMaxLength(1)
        self.plainText3.setObjectName("plainText3")
        self.plainText7 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText7.setGeometry(QtCore.QRect(50, 180, 51, 20))
        self.plainText7.setMaxLength(1)
        self.plainText7.setObjectName("plainText7")
        self.plainText6 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText6.setGeometry(QtCore.QRect(50, 160, 51, 20))
        self.plainText6.setMaxLength(1)
        self.plainText6.setObjectName("plainText6")
        self.plainText5 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText5.setGeometry(QtCore.QRect(50, 140, 51, 20))
        self.plainText5.setMaxLength(1)
        self.plainText5.setObjectName("plainText5")
        self.plainText8 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText8.setGeometry(QtCore.QRect(50, 200, 51, 20))
        self.plainText8.setMaxLength(1)
        self.plainText8.setObjectName("plainText8")
        self.plainText16 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText16.setGeometry(QtCore.QRect(50, 360, 51, 20))
        self.plainText16.setMaxLength(1)
        self.plainText16.setObjectName("plainText16")
        self.plainText11 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText11.setGeometry(QtCore.QRect(50, 260, 51, 20))
        self.plainText11.setMaxLength(1)
        self.plainText11.setObjectName("plainText11")
        self.plainText14 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText14.setGeometry(QtCore.QRect(50, 320, 51, 20))
        self.plainText14.setMaxLength(1)
        self.plainText14.setObjectName("plainText14")
        self.plainText10 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText10.setGeometry(QtCore.QRect(50, 240, 51, 20))
        self.plainText10.setMaxLength(1)
        self.plainText10.setObjectName("plainText10")
        self.plainText9 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText9.setGeometry(QtCore.QRect(50, 220, 51, 20))
        self.plainText9.setMaxLength(1)
        self.plainText9.setObjectName("plainText9")
        self.plainText13 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText13.setGeometry(QtCore.QRect(50, 300, 51, 20))
        self.plainText13.setMaxLength(1)
        self.plainText13.setObjectName("plainText13")
        self.plainText15 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText15.setGeometry(QtCore.QRect(50, 340, 51, 20))
        self.plainText15.setMaxLength(1)
        self.plainText15.setObjectName("plainText15")
        self.plainText12 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText12.setGeometry(QtCore.QRect(50, 280, 51, 20))
        self.plainText12.setMaxLength(1)
        self.plainText12.setObjectName("plainText12")
        self.plainText26 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText26.setGeometry(QtCore.QRect(50, 560, 51, 20))
        self.plainText26.setMaxLength(1)
        self.plainText26.setObjectName("plainText26")
        self.plainText24 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText24.setGeometry(QtCore.QRect(50, 520, 51, 20))
        self.plainText24.setMaxLength(1)
        self.plainText24.setObjectName("plainText24")
        self.plainText19 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText19.setGeometry(QtCore.QRect(50, 420, 51, 20))
        self.plainText19.setMaxLength(1)
        self.plainText19.setObjectName("plainText19")
        self.plainText22 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText22.setGeometry(QtCore.QRect(50, 480, 51, 20))
        self.plainText22.setMaxLength(1)
        self.plainText22.setObjectName("plainText22")
        self.plainText25 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText25.setGeometry(QtCore.QRect(50, 540, 51, 20))
        self.plainText25.setMaxLength(1)
        self.plainText25.setObjectName("plainText25")
        self.plainText18 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText18.setGeometry(QtCore.QRect(50, 400, 51, 20))
        self.plainText18.setMaxLength(1)
        self.plainText18.setObjectName("plainText18")
        self.plainText17 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText17.setGeometry(QtCore.QRect(50, 380, 51, 20))
        self.plainText17.setMaxLength(1)
        self.plainText17.setObjectName("plainText17")
        self.plainText21 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText21.setGeometry(QtCore.QRect(50, 460, 51, 20))
        self.plainText21.setMaxLength(1)
        self.plainText21.setObjectName("plainText21")
        self.plainText23 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText23.setGeometry(QtCore.QRect(50, 500, 51, 20))
        self.plainText23.setMaxLength(1)
        self.plainText23.setObjectName("plainText23")
        self.plainText20 = QtWidgets.QLineEdit(self.centralwidget)
        self.plainText20.setGeometry(QtCore.QRect(50, 440, 51, 20))
        self.plainText20.setMaxLength(1)
        self.plainText20.setObjectName("plainText20")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 30, 71, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 610, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.cipherText21 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText21.setGeometry(QtCore.QRect(190, 460, 51, 20))
        self.cipherText21.setMaxLength(1)
        self.cipherText21.setObjectName("cipherText21")
        self.cipherText11 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText11.setGeometry(QtCore.QRect(190, 260, 51, 20))
        self.cipherText11.setMaxLength(1)
        self.cipherText11.setObjectName("cipherText11")
        self.cipherText20 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText20.setGeometry(QtCore.QRect(190, 440, 51, 20))
        self.cipherText20.setMaxLength(1)
        self.cipherText20.setObjectName("cipherText20")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 610, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.cipherText8 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText8.setGeometry(QtCore.QRect(190, 200, 51, 20))
        self.cipherText8.setMaxLength(1)
        self.cipherText8.setObjectName("cipherText8")
        self.cipherText2 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText2.setGeometry(QtCore.QRect(190, 80, 51, 20))
        self.cipherText2.setMaxLength(1)
        self.cipherText2.setObjectName("cipherText2")
        self.cipherText23 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText23.setGeometry(QtCore.QRect(190, 500, 51, 20))
        self.cipherText23.setMaxLength(1)
        self.cipherText23.setObjectName("cipherText23")
        self.cipherText1 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText1.setGeometry(QtCore.QRect(190, 60, 51, 20))
        self.cipherText1.setMaxLength(1)
        self.cipherText1.setReadOnly(False)
        self.cipherText1.setObjectName("cipherText1")
        self.cipherText4 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText4.setGeometry(QtCore.QRect(190, 120, 51, 20))
        self.cipherText4.setMaxLength(1)
        self.cipherText4.setObjectName("cipherText4")
        self.cipherText12 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText12.setGeometry(QtCore.QRect(190, 280, 51, 20))
        self.cipherText12.setMaxLength(1)
        self.cipherText12.setObjectName("cipherText12")
        self.cipherText7 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText7.setGeometry(QtCore.QRect(190, 180, 51, 20))
        self.cipherText7.setMaxLength(1)
        self.cipherText7.setObjectName("cipherText7")
        self.cipherText17 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText17.setGeometry(QtCore.QRect(190, 380, 51, 20))
        self.cipherText17.setMaxLength(1)
        self.cipherText17.setObjectName("cipherText17")
        self.cipherText6 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText6.setGeometry(QtCore.QRect(190, 160, 51, 20))
        self.cipherText6.setMaxLength(1)
        self.cipherText6.setObjectName("cipherText6")
        self.cipherText14 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText14.setGeometry(QtCore.QRect(190, 320, 51, 20))
        self.cipherText14.setMaxLength(1)
        self.cipherText14.setObjectName("cipherText14")
        self.cipherText16 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText16.setGeometry(QtCore.QRect(190, 360, 51, 20))
        self.cipherText16.setMaxLength(1)
        self.cipherText16.setObjectName("cipherText16")
        self.cipherText9 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText9.setGeometry(QtCore.QRect(190, 220, 51, 20))
        self.cipherText9.setMaxLength(1)
        self.cipherText9.setObjectName("cipherText9")
        self.cipherText26 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText26.setGeometry(QtCore.QRect(190, 560, 51, 20))
        self.cipherText26.setMaxLength(1)
        self.cipherText26.setObjectName("cipherText26")
        self.cipherText25 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText25.setGeometry(QtCore.QRect(190, 540, 51, 20))
        self.cipherText25.setMaxLength(1)
        self.cipherText25.setObjectName("cipherText25")
        self.cipherText5 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText5.setGeometry(QtCore.QRect(190, 140, 51, 20))
        self.cipherText5.setMaxLength(1)
        self.cipherText5.setObjectName("cipherText5")
        self.cipherText10 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText10.setGeometry(QtCore.QRect(190, 240, 51, 20))
        self.cipherText10.setMaxLength(1)
        self.cipherText10.setObjectName("cipherText10")
        self.cipherText24 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText24.setGeometry(QtCore.QRect(190, 520, 51, 20))
        self.cipherText24.setMaxLength(1)
        self.cipherText24.setObjectName("cipherText24")
        self.cipherText3 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText3.setGeometry(QtCore.QRect(190, 100, 51, 20))
        self.cipherText3.setMaxLength(1)
        self.cipherText3.setObjectName("cipherText3")
        self.cipherText15 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText15.setGeometry(QtCore.QRect(190, 340, 51, 20))
        self.cipherText15.setMaxLength(1)
        self.cipherText15.setObjectName("cipherText15")
        self.cipherText22 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText22.setGeometry(QtCore.QRect(190, 480, 51, 20))
        self.cipherText22.setMaxLength(1)
        self.cipherText22.setObjectName("cipherText22")
        self.cipherText13 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText13.setGeometry(QtCore.QRect(190, 300, 51, 20))
        self.cipherText13.setMaxLength(1)
        self.cipherText13.setObjectName("cipherText13")
        self.cipherText18 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText18.setGeometry(QtCore.QRect(190, 400, 51, 20))
        self.cipherText18.setMaxLength(1)
        self.cipherText18.setObjectName("cipherText18")
        self.cipherText19 = QtWidgets.QLineEdit(self.centralwidget)
        self.cipherText19.setGeometry(QtCore.QRect(190, 420, 51, 20))
        self.cipherText19.setMaxLength(1)
        self.cipherText19.setObjectName("cipherText19")
        self.Texto_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.Texto_2.setGeometry(QtCore.QRect(300, 250, 481, 111))
        self.Texto_2.setObjectName("Texto_2")
        self.btnEncriptar = QtWidgets.QRadioButton(self.centralwidget)
        self.btnEncriptar.setGeometry(QtCore.QRect(490, 410, 82, 17))
        self.btnEncriptar.setObjectName("btnEncriptar")
        self.btnDesencriptar = QtWidgets.QRadioButton(self.centralwidget)
        self.btnDesencriptar.setGeometry(QtCore.QRect(490, 450, 121, 17))
        self.btnDesencriptar.setObjectName("btnDesencriptar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setShortcut("")
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered['bool'].connect(MainWindow.close)
        self.pushButton.clicked.connect(self.plainText1.clear)
        self.pushButton.clicked.connect(self.plainText2.clear)
        self.pushButton.clicked.connect(self.plainText3.clear)
        self.pushButton.clicked.connect(self.plainText4.clear)
        self.pushButton.clicked.connect(self.plainText5.clear)
        self.pushButton.clicked.connect(self.plainText6.clear)
        self.pushButton.clicked.connect(self.plainText7.clear)
        self.pushButton.clicked.connect(self.plainText8.clear)
        self.pushButton.clicked.connect(self.plainText9.clear)
        self.pushButton.clicked.connect(self.plainText10.clear)
        self.pushButton.clicked.connect(self.plainText11.clear)
        self.pushButton.clicked.connect(self.plainText12.clear)
        self.pushButton.clicked.connect(self.plainText13.clear)
        self.pushButton.clicked.connect(self.plainText14.clear)
        self.pushButton.clicked.connect(self.plainText15.clear)
        self.pushButton.clicked.connect(self.plainText16.clear)
        self.pushButton.clicked.connect(self.plainText17.clear)
        self.pushButton.clicked.connect(self.plainText18.clear)
        self.pushButton.clicked.connect(self.plainText19.clear)
        self.pushButton.clicked.connect(self.plainText20.clear)
        self.pushButton.clicked.connect(self.plainText21.clear)
        self.pushButton.clicked.connect(self.plainText22.clear)
        self.pushButton.clicked.connect(self.plainText23.clear)
        self.pushButton.clicked.connect(self.plainText24.clear)
        self.pushButton.clicked.connect(self.plainText25.clear)
        self.pushButton.clicked.connect(self.plainText26.clear)
        self.pushButton_2.clicked.connect(self.cipherText1.clear)
        self.pushButton_2.clicked.connect(self.cipherText2.clear)
        self.pushButton_2.clicked.connect(self.cipherText3.clear)
        self.pushButton_2.clicked.connect(self.cipherText4.clear)
        self.pushButton_2.clicked.connect(self.cipherText5.clear)
        self.pushButton_2.clicked.connect(self.cipherText6.clear)
        self.pushButton_2.clicked.connect(self.cipherText7.clear)
        self.pushButton_2.clicked.connect(self.cipherText8.clear)
        self.pushButton_2.clicked.connect(self.cipherText9.clear)
        self.pushButton_2.clicked.connect(self.cipherText10.clear)
        self.pushButton_2.clicked.connect(self.cipherText11.clear)
        self.pushButton_2.clicked.connect(self.cipherText12.clear)
        self.pushButton_2.clicked.connect(self.cipherText13.clear)
        self.pushButton_2.clicked.connect(self.cipherText14.clear)
        self.pushButton_2.clicked.connect(self.cipherText15.clear)
        self.pushButton_2.clicked.connect(self.cipherText16.clear)
        self.pushButton_2.clicked.connect(self.cipherText17.clear)
        self.pushButton_2.clicked.connect(self.cipherText18.clear)
        self.pushButton_2.clicked.connect(self.cipherText19.clear)
        self.pushButton_2.clicked.connect(self.cipherText20.clear)
        self.pushButton_2.clicked.connect(self.cipherText21.clear)
        self.pushButton_2.clicked.connect(self.cipherText22.clear)
        self.pushButton_2.clicked.connect(self.cipherText23.clear)
        self.pushButton_2.clicked.connect(self.cipherText24.clear)
        self.pushButton_2.clicked.connect(self.cipherText25.clear)
        self.pushButton_2.clicked.connect(self.cipherText26.clear)
        self.btnLimpiar.clicked.connect(self.Texto.clear)
        self.btnLimpiar.clicked.connect(self.Texto_2.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Texto, self.btnLimpiar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnLimpiar.setText(_translate("MainWindow", "Limpiar Mensaje"))
        self.plainText1.setText(_translate("MainWindow", "A"))
        self.plainText2.setText(_translate("MainWindow", "B"))
        self.plainText4.setText(_translate("MainWindow", "D"))
        self.plainText3.setText(_translate("MainWindow", "C"))
        self.plainText7.setText(_translate("MainWindow", "G"))
        self.plainText6.setText(_translate("MainWindow", "F"))
        self.plainText5.setText(_translate("MainWindow", "E"))
        self.plainText8.setText(_translate("MainWindow", "H"))
        self.plainText16.setText(_translate("MainWindow", "P"))
        self.plainText11.setText(_translate("MainWindow", "K"))
        self.plainText14.setText(_translate("MainWindow", "N"))
        self.plainText10.setText(_translate("MainWindow", "J"))
        self.plainText9.setText(_translate("MainWindow", "I"))
        self.plainText13.setText(_translate("MainWindow", "M"))
        self.plainText15.setText(_translate("MainWindow", "O"))
        self.plainText12.setText(_translate("MainWindow", "L"))
        self.plainText26.setText(_translate("MainWindow", "Z"))
        self.plainText24.setText(_translate("MainWindow", "X"))
        self.plainText19.setText(_translate("MainWindow", "S"))
        self.plainText22.setText(_translate("MainWindow", "V"))
        self.plainText25.setText(_translate("MainWindow", "Y"))
        self.plainText18.setText(_translate("MainWindow", "R"))
        self.plainText17.setText(_translate("MainWindow", "Q"))
        self.plainText21.setText(_translate("MainWindow", "U"))
        self.plainText23.setText(_translate("MainWindow", "W"))
        self.plainText20.setText(_translate("MainWindow", "T"))
        self.label.setText(_translate("MainWindow", "PLAINTEXT:"))
        self.label_2.setText(_translate("MainWindow", "CIPHERTEXT:"))
        self.pushButton.setText(_translate("MainWindow", "Limpiar"))
        self.cipherText21.setText(_translate("MainWindow", "U"))
        self.cipherText11.setText(_translate("MainWindow", "K"))
        self.cipherText20.setText(_translate("MainWindow", "T"))
        self.pushButton_2.setText(_translate("MainWindow", "Limpiar"))
        self.cipherText8.setText(_translate("MainWindow", "H"))
        self.cipherText2.setText(_translate("MainWindow", "B"))
        self.cipherText23.setText(_translate("MainWindow", "W"))
        self.cipherText1.setText(_translate("MainWindow", "A"))
        self.cipherText4.setText(_translate("MainWindow", "D"))
        self.cipherText12.setText(_translate("MainWindow", "L"))
        self.cipherText7.setText(_translate("MainWindow", "G"))
        self.cipherText17.setText(_translate("MainWindow", "Q"))
        self.cipherText6.setText(_translate("MainWindow", "F"))
        self.cipherText14.setText(_translate("MainWindow", "N"))
        self.cipherText16.setText(_translate("MainWindow", "P"))
        self.cipherText9.setText(_translate("MainWindow", "I"))
        self.cipherText26.setText(_translate("MainWindow", "Z"))
        self.cipherText25.setText(_translate("MainWindow", "Y"))
        self.cipherText5.setText(_translate("MainWindow", "E"))
        self.cipherText10.setText(_translate("MainWindow", "J"))
        self.cipherText24.setText(_translate("MainWindow", "X"))
        self.cipherText3.setText(_translate("MainWindow", "C"))
        self.cipherText15.setText(_translate("MainWindow", "O"))
        self.cipherText22.setText(_translate("MainWindow", "V"))
        self.cipherText13.setText(_translate("MainWindow", "M"))
        self.cipherText18.setText(_translate("MainWindow", "R"))
        self.cipherText19.setText(_translate("MainWindow", "S"))
        self.btnEncriptar.setText(_translate("MainWindow", "ENCRIPTAR"))
        self.btnDesencriptar.setText(_translate("MainWindow", "DESENCRIPTAR"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

